# fly.toml app configuration file generated for ranchoulvtgz on 2023-08-16T15:10:17-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ranchoulvtgz"
primary_region = "qro"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  DB_SSL="true"
  DB_SSL_MODE="require"
  DB_CONNECTION="mysql"
  DB_HOST="primary.ranchoulvtgz-mysql--clkdf2qbhk5b.addon.code.run"
  DB_PORT="28330"
  DB_DATABASE="5642f69ef80f"
  DB_USERNAME="668698736b1fc7aa"
  DB_PASSWORD="6540a557883cf8c48bdf54c0efee18"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


